<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\User;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get admin and penulis users
        $adminUser = User::where('role', 'admin')->first();
        $penulisUser = User::where('role', 'penulis')->first();
        
        if (!$adminUser || !$penulisUser) {
            $this->command->error('Admin and Penulis users must exist before seeding events');
            return;
        }

        $events = [
            [
                'title' => 'Workshop Digital Marketing 2025',
                'slug' => 'workshop-digital-marketing-2025',
                'description' => 'Workshop lengkap tentang strategi pemasaran digital terkini untuk UMKM dan startup.',
                'content' => "Dalam era digital yang semakin berkembang pesat, kemampuan untuk menguasai digital marketing menjadi kunci sukses bagi setiap bisnis. Workshop Digital Marketing 2025 hadir untuk memberikan pemahaman mendalam tentang strategi pemasaran digital yang efektif.\n\nMateri yang akan dibahas:\n- Fundamentals Digital Marketing\n- Social Media Marketing Strategy\n- Search Engine Optimization (SEO)\n- Google Ads & Facebook Ads\n- Content Marketing\n- Email Marketing\n- Analytics & Performance Measurement\n\nWorkshop ini cocok untuk:\n- Pemilik UMKM\n- Marketing Staff\n- Startup Founder\n- Freelancer\n- Mahasiswa\n\nFasilitas:\n- Materi pembelajaran lengkap\n- Sertifikat peserta\n- Lunch & Coffee Break\n- Networking session\n- 1 bulan konsultasi gratis",
                'start_date' => Carbon::now()->addDays(15)->setTime(9, 0),
                'end_date' => Carbon::now()->addDays(15)->setTime(17, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Gedung Creative Hub Jakarta',
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat, DKI Jakarta 10220',
                'category' => 'Workshop',
                'tags' => ['digital marketing', 'workshop', 'business', 'UMKM'],
                'event_type' => 'workshop',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 50,
                'registration_fee' => 350000,
                'registration_deadline' => Carbon::now()->addDays(10),
                'contact_person' => 'Sarah Marketing',
                'contact_email' => 'sarah@example.com',
                'contact_phone' => '08123456789',
                'website' => 'https://digitalworkshop.example.com',
                'author_id' => $adminUser->id,
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'view_count' => 125,
                'meta_title' => 'Workshop Digital Marketing 2025 - Tingkatkan Skill Pemasaran Digital Anda',
                'meta_description' => 'Ikuti workshop digital marketing terlengkap 2025. Pelajari strategi SEO, Social Media, Google Ads, dan Content Marketing. Daftar sekarang!',
                'meta_keywords' => 'workshop digital marketing, pelatihan SEO, social media marketing, google ads',
                'og_title' => 'Workshop Digital Marketing 2025',
                'og_description' => 'Workshop lengkap digital marketing untuk UMKM dan startup. Materi terkini, instruktur berpengalaman, sertifikat resmi.',
            ],
            [
                'title' => 'Seminar Kewirausahaan: From Zero to Hero',
                'slug' => 'seminar-kewirausahaan-from-zero-to-hero',
                'description' => 'Seminar inspiratif tentang perjalanan membangun bisnis dari nol hingga sukses.',
                'content' => "Seminar Kewirausahaan 'From Zero to Hero' menghadirkan para pengusaha sukses untuk berbagi pengalaman dan strategi membangun bisnis dari nol.\n\nPembicara:\n- Budi Santoso (Founder StartupXYZ)\n- Lisa Chen (CEO TechCorp)\n- Ahmad Rahman (Investor & Mentor)\n\nTopik Pembahasan:\n1. Mindset Entrepreneur yang Benar\n2. Cara Menemukan Ide Bisnis yang Tepat\n3. Strategi Funding dan Investment\n4. Building Team yang Solid\n5. Scaling Business untuk Growth\n6. Mengatasi Tantangan dan Kegagalan\n\nTarget Peserta:\n- Calon entrepreneur\n- Startup founder\n- Business owner\n- Mahasiswa\n- Professional yang ingin berbisnis\n\nKeuntungan Mengikuti:\n- Insight dari pengusaha sukses\n- Networking dengan sesama entrepreneur\n- E-book panduan bisnis\n- Template business plan\n- Akses ke komunitas entrepreneur",
                'start_date' => Carbon::now()->addDays(8)->setTime(13, 0),
                'end_date' => Carbon::now()->addDays(8)->setTime(17, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Auditorium Universitas Indonesia',
                'address' => 'Kampus UI Depok, Jl. Margonda Raya, Depok, Jawa Barat 16424',
                'category' => 'Seminar',
                'tags' => ['kewirausahaan', 'seminar', 'startup', 'business'],
                'event_type' => 'seminar',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 200,
                'registration_fee' => 0,
                'registration_deadline' => Carbon::now()->addDays(5),
                'contact_person' => 'Tim Event UI',
                'contact_email' => 'event@ui.ac.id',
                'contact_phone' => '021-7863479',
                'website' => 'https://entrepreneur.ui.ac.id',
                'author_id' => $penulisUser->id,
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'view_count' => 89,
                'meta_title' => 'Seminar Kewirausahaan From Zero to Hero - Gratis!',
                'meta_description' => 'Seminar gratis tentang kewirausahaan dengan pembicara pengusaha sukses. Pelajari cara membangun bisnis dari nol. Daftar sekarang!',
                'meta_keywords' => 'seminar kewirausahaan, startup, entrepreneur, bisnis',
                'og_title' => 'Seminar Kewirausahaan From Zero to Hero',
                'og_description' => 'Seminar inspiratif dengan para pengusaha sukses. Gratis untuk umum. Tempat terbatas!',
            ],
            [
                'title' => 'Festival Teknologi Indonesia 2025',
                'slug' => 'festival-teknologi-indonesia-2025',
                'description' => 'Festival teknologi terbesar di Indonesia dengan pameran, kompetisi, dan workshop.',
                'content' => "Festival Teknologi Indonesia 2025 merupakan acara tahunan terbesar yang menggabungkan pameran teknologi, kompetisi inovasi, dan serangkaian workshop edukatif.\n\nHighlight Acara:\n\n🏆 KOMPETISI INOVASI\n- Hackathon 48 jam\n- Startup Pitch Competition\n- AI/ML Challenge\n- IoT Innovation Contest\n\n🔬 PAMERAN TEKNOLOGI\n- Showcase startup terbaru\n- Demo produk teknologi\n- Innovation gallery\n- Tech company booth\n\n📚 WORKSHOP & SEMINAR\n- Introduction to AI\n- Blockchain for Beginners\n- Mobile App Development\n- Cybersecurity Awareness\n- Data Science Workshop\n\n🎭 ENTERTAINMENT\n- Tech Talk dengan praktisi\n- Robot competition\n- VR/AR experience\n- Drone showcase\n\nHadiah Kompetisi:\n- Juara 1: Rp 50.000.000\n- Juara 2: Rp 30.000.000\n- Juara 3: Rp 20.000.000\n- Best Innovation Award\n- People's Choice Award\n\nFasilitas:\n- Free WiFi high speed\n- Food court\n- Charging station\n- Networking lounge\n- Live streaming",
                'start_date' => Carbon::now()->addDays(30)->setTime(8, 0),
                'end_date' => Carbon::now()->addDays(32)->setTime(18, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Jakarta Convention Center (JCC)',
                'address' => 'Jl. Gatot Subroto, Senayan, Jakarta Pusat, DKI Jakarta 10270',
                'category' => 'Festival',
                'tags' => ['teknologi', 'festival', 'kompetisi', 'inovasi', 'startup'],
                'event_type' => 'festival',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 5000,
                'registration_fee' => 150000,
                'registration_deadline' => Carbon::now()->addDays(25),
                'contact_person' => 'Festival Committee',
                'contact_email' => 'info@festivalteknologi.id',
                'contact_phone' => '021-5555-1234',
                'website' => 'https://festivalteknologi.id',
                'author_id' => $adminUser->id,
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'view_count' => 234,
                'meta_title' => 'Festival Teknologi Indonesia 2025 - Event Tech Terbesar!',
                'meta_description' => 'Festival teknologi terbesar Indonesia dengan kompetisi, pameran, dan workshop. Hadiah jutaan rupiah. JCC Jakarta 30 Maret - 1 April 2025.',
                'meta_keywords' => 'festival teknologi, kompetisi startup, hackathon, inovasi teknologi',
                'og_title' => 'Festival Teknologi Indonesia 2025',
                'og_description' => 'Festival teknologi terbesar dengan kompetisi berhadiah puluhan juta rupiah. Jangan lewatkan!',
            ],
            [
                'title' => 'Training Public Speaking untuk Profesional',
                'slug' => 'training-public-speaking-untuk-profesional',
                'description' => 'Pelatihan intensif public speaking untuk meningkatkan kemampuan presentasi dan komunikasi.',
                'content' => "Training Public Speaking untuk Profesional dirancang khusus untuk meningkatkan kemampuan berbicara di depan umum dan presentasi yang efektif.\n\nProgram Training:\n\nDAY 1: Foundation\n- Understanding Your Audience\n- Overcoming Stage Fright\n- Voice and Body Language\n- Basic Presentation Structure\n\nDAY 2: Advanced Techniques\n- Storytelling in Presentation\n- Using Visual Aids Effectively\n- Handling Q&A Sessions\n- Persuasive Speaking\n\nDAY 3: Practice & Feedback\n- Individual Presentation Practice\n- Peer Review and Feedback\n- Video Analysis\n- Personal Action Plan\n\nMetode Training:\n- Interactive workshop\n- Role playing\n- Video recording & analysis\n- Group discussion\n- One-on-one coaching\n\nTrainer Profile:\n- Dr. Maya Sari (Communication Expert)\n- 15+ tahun pengalaman\n- Certified International Speaker\n- Author of 'Speak with Confidence'\n\nTarget Peserta:\n- Manager & Executive\n- Sales Professional\n- Consultant\n- Trainer & Educator\n- Public Figure\n\nBenefit:\n- Confidence boost\n- Professional credibility\n- Career advancement\n- Better networking\n- Leadership skills",
                'start_date' => Carbon::now()->addDays(20)->setTime(9, 0),
                'end_date' => Carbon::now()->addDays(22)->setTime(17, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Hotel Santika Jakarta',
                'address' => 'Jl. M.H. Thamrin No. 53, Jakarta Pusat, DKI Jakarta 10350',
                'category' => 'Training',
                'tags' => ['public speaking', 'training', 'professional development', 'communication'],
                'event_type' => 'training',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 25,
                'registration_fee' => 2500000,
                'registration_deadline' => Carbon::now()->addDays(15),
                'contact_person' => 'Lisa Training Center',
                'contact_email' => 'lisa@trainingcenter.co.id',
                'contact_phone' => '021-3456-7890',
                'website' => 'https://publicspeaking.trainingcenter.co.id',
                'author_id' => $penulisUser->id,
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'view_count' => 67,
                'meta_title' => 'Training Public Speaking Profesional - 3 Hari Intensif',
                'meta_description' => 'Pelatihan public speaking intensif 3 hari untuk profesional. Trainer berpengalaman, metode interaktif, sertifikat resmi.',
                'meta_keywords' => 'training public speaking, pelatihan presentasi, komunikasi profesional',
                'og_title' => 'Training Public Speaking untuk Profesional',
                'og_description' => 'Tingkatkan kemampuan public speaking Anda dengan training intensif 3 hari. Limited seats!',
            ],
            [
                'title' => 'Meetup Developer Jakarta: React & Node.js',
                'slug' => 'meetup-developer-jakarta-react-nodejs',
                'description' => 'Meetup bulanan untuk developer Jakarta membahas React dan Node.js terbaru.',
                'content' => "Developer Jakarta Meetup kembali hadir dengan topik menarik tentang teknologi React dan Node.js yang sedang trending di industri.\n\nAgenda Meetup:\n\n🕐 18:30 - 19:00 | Registration & Networking\n- Welcome drink\n- Name tag & goodie bag\n- Networking session\n\n🕐 19:00 - 19:45 | Session 1\n'React 18 New Features & Performance Optimization'\nSpeaker: Andi Pratama (Senior Frontend Developer at Tokopedia)\n\n🕐 19:45 - 20:00 | Break\n- Coffee break\n- Networking\n\n🕐 20:00 - 20:45 | Session 2\n'Building Scalable API with Node.js & Express'\nSpeaker: Sari Dewi (Backend Engineer at Gojek)\n\n🕐 20:45 - 21:15 | Q&A & Discussion\n- Open discussion\n- Job opportunities sharing\n- Next meetup planning\n\nWho Should Attend:\n- Frontend/Backend Developer\n- Full Stack Developer\n- Tech Lead/Engineering Manager\n- Computer Science Student\n- Anyone interested in web development\n\nWhat You'll Get:\n- Latest tech insights\n- Networking opportunities\n- Free snacks & drinks\n- Exclusive developer community access\n- Job referral opportunities\n\nRequirements:\n- Basic JavaScript knowledge\n- Laptop (optional)\n- Enthusiasm to learn!",
                'start_date' => Carbon::now()->addDays(12)->setTime(18, 30),
                'end_date' => Carbon::now()->addDays(12)->setTime(21, 30),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'WeWork Equity Tower',
                'address' => 'Equity Tower, Jl. Jenderal Sudirman Kav. 52-53, Jakarta Selatan 12190',
                'category' => 'Meetup',
                'tags' => ['developer', 'meetup', 'react', 'nodejs', 'javascript'],
                'event_type' => 'meetup',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 80,
                'registration_fee' => 0,
                'registration_deadline' => Carbon::now()->addDays(10),
                'contact_person' => 'Jakarta Developer Community',
                'contact_email' => 'hello@jakartadev.org',
                'contact_phone' => '0812-3456-7890',
                'website' => 'https://jakartadev.org/meetup',
                'author_id' => $adminUser->id,
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'view_count' => 156,
                'meta_title' => 'Meetup Developer Jakarta - React & Node.js',
                'meta_description' => 'Meetup gratis untuk developer Jakarta. Bahas React 18 dan Node.js dengan speaker dari Tokopedia & Gojek. Daftar sekarang!',
                'meta_keywords' => 'meetup developer, react meetup, nodejs jakarta, developer community',
                'og_title' => 'Developer Meetup Jakarta: React & Node.js',
                'og_description' => 'Join meetup developer Jakarta membahas React & Node.js. Speaker dari Tokopedia & Gojek. Gratis!',
            ],
            [
                'title' => 'Conference: Future of Artificial Intelligence',
                'slug' => 'conference-future-of-artificial-intelligence',
                'description' => 'Konferensi internasional tentang masa depan kecerdasan buatan dan implementasinya.',
                'content' => "AI Conference 2025 menghadirkan para ahli dan praktisi terkemuka untuk membahas perkembangan terkini dan masa depan Artificial Intelligence.\n\nKeynote Speakers:\n- Dr. Andrew Ng (Founder Coursera, Former Stanford AI Lab)\n- Prof. Fei-Fei Li (Stanford University)\n- Satya Nadella (CEO Microsoft) - Virtual\n- Dr. Kai-Fu Lee (CEO Sinovation Ventures)\n\nTracks & Sessions:\n\n🤖 AI FUNDAMENTALS\n- Machine Learning Basics\n- Deep Learning Applications\n- Natural Language Processing\n- Computer Vision\n\n🏭 AI IN INDUSTRY\n- AI in Healthcare\n- Autonomous Vehicles\n- Financial AI Applications\n- Smart Manufacturing\n\n🔬 RESEARCH & INNOVATION\n- Latest AI Research\n- Quantum AI\n- AI Ethics & Governance\n- AGI Development\n\n💼 BUSINESS & STRATEGY\n- AI Strategy for Business\n- ROI of AI Implementation\n- AI Startup Ecosystem\n- Future Job Market\n\nWorkshops (Additional Fee):\n- Hands-on TensorFlow\n- Building Chatbots\n- AI for Data Analysis\n- Computer Vision Projects\n\nWho Should Attend:\n- AI Researchers\n- Data Scientists\n- Software Engineers\n- Product Managers\n- Business Leaders\n- Students & Academics\n\nConference Benefits:\n- 2 days of cutting-edge content\n- Networking with 1000+ professionals\n- Access to latest AI tools & platforms\n- Certificate of attendance\n- Workshop materials\n- 1-year access to recorded sessions",
                'start_date' => Carbon::now()->addDays(45)->setTime(8, 0),
                'end_date' => Carbon::now()->addDays(46)->setTime(18, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Shangri-La Hotel Jakarta',
                'address' => 'Jl. Jenderal Sudirman Kav. 1, Jakarta Pusat, DKI Jakarta 10220',
                'category' => 'Conference',
                'tags' => ['AI', 'artificial intelligence', 'conference', 'technology', 'research'],
                'event_type' => 'conference',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 1000,
                'registration_fee' => 5500000,
                'registration_deadline' => Carbon::now()->addDays(40),
                'contact_person' => 'AI Conference Committee',
                'contact_email' => 'info@aiconference.id',
                'contact_phone' => '+62-21-2345-6789',
                'website' => 'https://aiconference.id',
                'author_id' => $adminUser->id,
                'is_featured' => true,
                'published_at' => Carbon::now(),
                'view_count' => 412,
                'meta_title' => 'AI Conference 2025 - Future of Artificial Intelligence',
                'meta_description' => 'Konferensi AI terbesar di Asia Tenggara. Speaker internasional, 2 hari intensive learning. Early bird discount tersedia!',
                'meta_keywords' => 'AI conference, artificial intelligence, machine learning conference, technology summit',
                'og_title' => 'AI Conference 2025',
                'og_description' => 'Join 1000+ professionals in the biggest AI conference in Southeast Asia. International speakers, cutting-edge content.',
            ],
            [
                'title' => 'Workshop Fotografi: Street Photography Fundamentals',
                'slug' => 'workshop-fotografi-street-photography-fundamentals',
                'description' => 'Workshop fotografi jalanan untuk pemula hingga menengah dengan fotografer profesional.',
                'content' => "Workshop Street Photography hadir untuk para pecinta fotografi yang ingin mendalami seni memotret kehidupan sehari-hari di jalanan.\n\nMentor Workshop:\n📸 Budi Photographer\n- 12+ tahun pengalaman street photography\n- Juara World Street Photography Awards 2023\n- Published in National Geographic\n- Instagram: @budistreetphoto (500K followers)\n\nProgram Workshop:\n\n🌅 MORNING SESSION (09:00 - 12:00)\n- Teori Street Photography\n  * Sejarah dan evolusi\n  * Karakteristik dan style\n  * Ethics in street photography\n  * Legal aspects\n\n- Camera Settings untuk Street\n  * Exposure settings\n  * Focus techniques\n  * ISO management\n  * Lens selection\n\n🌆 AFTERNOON SESSION (13:00 - 17:00)\n- Praktek Lapangan di Old Town Jakarta\n  * Candid photography\n  * Composition techniques\n  * Working with natural light\n  * Interacting with subjects\n\n- Review & Critique Session\n  * Photo selection\n  * Constructive feedback\n  * Post-processing tips\n  * Portfolio building\n\nWhat to Bring:\n- DSLR/Mirrorless camera\n- Memory cards (min 32GB)\n- Extra batteries\n- Comfortable walking shoes\n- Notebook & pen\n\nWorkshop Benefits:\n- Intensive mentoring\n- Certificate of completion\n- Access to exclusive Facebook group\n- Free Lightroom presets\n- Photo printing voucher\n- Networking with fellow photographers\n\nLevel: Beginner to Intermediate\nClass Size: Limited to 15 participants",
                'start_date' => Carbon::now()->addDays(25)->setTime(9, 0),
                'end_date' => Carbon::now()->addDays(25)->setTime(17, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Kota Tua Jakarta',
                'address' => 'Meeting Point: Museum Fatahillah, Jl. Taman Fatahillah No. 1, Jakarta Barat',
                'category' => 'Workshop',
                'tags' => ['fotografi', 'workshop', 'street photography', 'photography'],
                'event_type' => 'workshop',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 15,
                'registration_fee' => 750000,
                'registration_deadline' => Carbon::now()->addDays(20),
                'contact_person' => 'Photo Workshop Indonesia',
                'contact_email' => 'info@photoworkshop.id',
                'contact_phone' => '0856-1234-5678',
                'website' => 'https://photoworkshop.id/street',
                'author_id' => $penulisUser->id,
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'view_count' => 78,
                'meta_title' => 'Workshop Street Photography Jakarta - Belajar dari Pro',
                'meta_description' => 'Workshop fotografi jalanan dengan mentor berpengalaman. Teori + praktek di Kota Tua. Limited seats. Daftar sekarang!',
                'meta_keywords' => 'workshop fotografi, street photography, kursus fotografi, foto jalanan',
                'og_title' => 'Workshop Street Photography Fundamentals',
                'og_description' => 'Pelajari seni street photography dari fotografer profesional. Hands-on workshop di Kota Tua Jakarta.',
            ],
            [
                'title' => 'Networking Night: Startup Ecosystem Jakarta',
                'slug' => 'networking-night-startup-ecosystem-jakarta',
                'description' => 'Acara networking malam untuk startup founders, investors, dan ecosystem players.',
                'content' => "Startup Networking Night adalah acara bulanan yang mempertemukan para pemain ekosistem startup Jakarta dalam suasana santai dan informal.\n\nWho Will Attend:\n\n👨‍💼 STARTUP FOUNDERS\n- Early stage startup founders\n- Serial entrepreneurs\n- Solopreneurs\n- Side project builders\n\n💰 INVESTORS & VCs\n- Angel investors\n- Venture Capital partners\n- Corporate VCs\n- Government funding reps\n\n🛠️ ECOSYSTEM PLAYERS\n- Accelerator & incubator teams\n- Startup service providers\n- Tech talent\n- Industry mentors\n\nEvent Format:\n\n🍸 18:30 - 19:30 | Welcome Reception\n- Registration & name tags\n- Welcome drinks & canapés\n- Ice breaker activities\n- Speed networking session\n\n🎤 19:30 - 20:15 | Fireside Chat\n'Building Sustainable Startup Ecosystem in Indonesia'\nGuests:\n- Willson Cuaca (Managing Partner, East Ventures)\n- Melissa Siska (Co-founder, Sorabel)\n- Moderator: Rudiantara (Former Minister of Communication)\n\n🥂 20:15 - 22:00 | Open Networking\n- Free flow networking\n- Startup pitching corner\n- Investor meet & greet\n- Job matching session\n- Demo showcase area\n\nSpecial Features:\n- Startup showcase booth\n- Investment matching app\n- Business card scanner\n- Follow-up WhatsApp group\n- Next event priority access\n\nDress Code: Smart Casual\nNetworking Tools: Bring business cards & pitch deck (digital)\n\nWhat's Included:\n- Premium networking experience\n- Quality F&B throughout event\n- Access to exclusive investor network\n- Follow-up networking tools\n- Community membership\n\nPerfect for:\n- First-time entrepreneurs\n- Experienced founders seeking funding\n- Investors looking for deals\n- Anyone passionate about startups",
                'start_date' => Carbon::now()->addDays(18)->setTime(18, 30),
                'end_date' => Carbon::now()->addDays(18)->setTime(22, 0),
                'is_all_day' => false,
                'timezone' => 'Asia/Jakarta',
                'location' => 'Cloud Lounge SCBD',
                'address' => 'Equity Tower 40th Floor, Jl. Jenderal Sudirman Kav. 52-53, Jakarta Selatan',
                'category' => 'Networking',
                'tags' => ['networking', 'startup', 'entrepreneur', 'investor', 'ecosystem'],
                'event_type' => 'networking',
                'status' => 'published',
                'requires_registration' => true,
                'max_participants' => 120,
                'registration_fee' => 250000,
                'registration_deadline' => Carbon::now()->addDays(15),
                'contact_person' => 'Jakarta Startup Hub',
                'contact_email' => 'network@jakartastartuphub.com',
                'contact_phone' => '021-8888-9999',
                'website' => 'https://jakartastartuphub.com/networking',
                'author_id' => $adminUser->id,
                'is_featured' => false,
                'published_at' => Carbon::now(),
                'view_count' => 93,
                'meta_title' => 'Startup Networking Night Jakarta - Connect with Ecosystem',
                'meta_description' => 'Networking eksklusif untuk startup founders & investors di Jakarta. Fireside chat, speed networking, startup showcase. SCBD venue.',
                'meta_keywords' => 'startup networking, entrepreneur meetup, investor networking, startup ecosystem jakarta',
                'og_title' => 'Startup Networking Night Jakarta',
                'og_description' => 'Premium networking event for startup ecosystem. Meet founders, investors, and industry players in Jakarta.',
            ]
        ];

        foreach ($events as $eventData) {
            Event::create($eventData);
        }

        $this->command->info('Events seeded successfully!');
        $this->command->info('Created ' . count($events) . ' sample events');
    }
}
